# Generated by Django 5.2.3 on 2025-07-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_cart_client_cart_user_alter_cart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
