# Generated by Django 5.2.3 on 2025-07-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_available_sizes_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'size')},
        ),
    ]
